version: '3.9'

services:
  db:
    image: mysql:5.7.22
    restart: always
    volumes:
      - /opt/.db_data:/var/lib/mysql
    environment:
       MYSQL_DATABASE: db
       MYSQL_USER: root
       MYSQL_PASSWORD: root
       MYSQL_ROOT_PASSWORD: root
    networks:
      - default
  web:
    container_name: "cronos-backend"
    build: .
    command: sh -c './wait-for db:3306 -- python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - default
    depends_on:
      - db
networks:
  default: